[2025-07-11T19:25:11.965+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-11T19:25:12.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.training_task manual__2025-07-11T19:25:09.868365+00:00 [queued]>
[2025-07-11T19:25:12.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.training_task manual__2025-07-11T19:25:09.868365+00:00 [queued]>
[2025-07-11T19:25:12.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-11T19:25:12.040+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): training_task> on 2025-07-11 19:25:09.868365+00:00
[2025-07-11T19:25:12.049+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2025-07-11T19:25:12.053+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'training_task', 'manual__2025-07-11T19:25:09.868365+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpsjz0p56y']
[2025-07-11T19:25:12.057+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask training_task
[2025-07-11T19:25:12.119+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.training_task manual__2025-07-11T19:25:09.868365+00:00 [running]> on host e1cb5f596152
[2025-07-11T19:25:12.239+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ebrahim Emad' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='training_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T19:25:09.868365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-11T19:25:09.868365+00:00'
[2025-07-11T19:25:12.239+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-11T19:25:12.262+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix:///var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2025-07-11T19:25:12.262+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-11T19:25:12.275+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 492, in execute
    if self.force_pull or not self.cli.images(name=self.image):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 362, in cli
    return self.hook.api_client
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-07-11T19:25:12.280+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=training_task, run_id=manual__2025-07-11T19:25:09.868365+00:00, execution_date=20250711T192509, start_date=20250711T192512, end_date=20250711T192512
[2025-07-11T19:25:12.295+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task training_task (Failed to establish connection to any given Docker hosts.; 282)
[2025-07-11T19:25:12.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-11T19:25:12.371+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-11T19:25:12.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
